### ISSUE TITLE
直接下載的Demo檔案不能run

### ISSUE THREAD

**Issue by g001613001** [yonient/KEImageLoopView#1]
錯誤訊息如下：
line 2: /usr/local/bin/carthage: No such file or directory

**Comment by yonient** [comment]
需要在電腦上安裝 carthage 或者在 target 的 build phrase 里面把 run script 删掉喔

**Comment by g001613001** [comment]
刪除 run script後跑起來出現
dyld: Library not loaded: @rpath/WebImage.framework/WebImage
  Referenced from: /Users/Daniel/Library/Developer/CoreSimulator/Devices/87A8413C-2BE2-42BE-8950-4637C91F33A7/data/Containers/Bundle/Application/0878AB8C-2CC7-464B-BA40-1BC430B33F91/KEImageLoopView.app/KEImageLoopView
  Reason: image not found

**Comment by yonient** [comment]
在 Link Binary With Libraries 裡面把 WebImage 包設為 Optional 再試一下呢
